### ISSUE TITLE
Intellisense not working for .cake files in subfolders

### ISSUE THREAD

**Issue by Marusyk** [cake-build/bakery#105]
Here are some repro steps 

- Create subfolder with name __cake__ in root folder of project
- Add __build.cake__, __build.ps1__ files to  __cake__ folder
- Add subfolder __tools__ to  __cake__ folder
- Add **packages.config** file like:

```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
    <package id="Cake" version="0.28.0" />
    <package id="Cake.Bakery" version="0.3.0" />
</packages>

```
![screenshot_1](https://user-images.githubusercontent.com/9221694/43550337-e6d7fac6-95eb-11e8-9ba9-623610d9542b.png)

- Run `.\build.ps1`
![screenshot_2](https://user-images.githubusercontent.com/9221694/43550406-21492fe0-95ec-11e8-9511-e9b76befffef.png)

- Restart VS Code

After restart and reopen of the workspace, it should show intellisense for .\cake\build.cake
but it does not

[omnisharp-logs.txt](https://github.com/cake-build/bakery/files/2251210/omnisharp-logs.txt)

**Comment by Marusyk** [comment]
Issue #79

**Comment by mholo65** [comment]
@Marusyk,

do you have a `cake.config` file in the root folder, containing the following:
```ini
[Paths]
Tools=./cake/tools
Addins=./cake/tools/Addins
Modules=./cake/tools/Modules
```

**Comment by Marusyk** [comment]
No, I didn't know about that. Thanks. 

There are any documentations about that?
