### ISSUE TITLE
Update to O# Mono 5.18 in tests

### ISSUE THREAD

**Issue by bjorkstromm** [cake-build/bakery#114]
See https://github.com/OmniSharp/omnisharp-roslyn/pull/1444

**Comment by devlead** [comment]
@bjorkstromm Is this still relevant since we shifted to using the mono from their release?
https://github.com/cake-build/bakery/blob/26195306a987e9cd4c2505c1195204f4dc6695e0/recipe.cake#L39-L42

**Comment by bjorkstromm** [comment]
> @bjorkstromm Is this still relevant since we shifted to using the mono from their release?
> https://github.com/cake-build/bakery/blob/26195306a987e9cd4c2505c1195204f4dc6695e0/recipe.cake#L39-L42

Nope, this can be closed.
