### ISSUE TITLE
Does not work with Cake installed with Choco

### ISSUE THREAD

**Issue by bjorkstromm** [cake-build/bakery#115]
https://github.com/cake-build/bakery/blob/develop/src/Cake.Scripting/CodeGen/CakeScriptGenerator.cs#L243

Due to the shims provided by Choco, `Cake.Core.dll` and `Cake.Common.dll` does not sit next to the `Cake.exe` found in path (as this is the shim).

See:
```
c:\\Users\\mb\\src\\tmp\\lsp-test\\build.cake will be ignored due to an following error - System.IO.FileNotFoundException: Cake is not installed. Path C:/ProgramData/chocolatey/bin/Cake.Core.dll does not exist.
   at OmniSharp.Cake.CakeProjectSystem.GetProject(CakeScript cakeScript, String filePath) in C:\\Users\\mb\\src\\gh\\omnisharp-roslyn\\src\\OmniSharp.Cake\\CakeProjectSystem.cs:line 277
   at OmniSharp.Cake.CakeProjectSystem.AddCakeFile(String cakeFilePath) in C:\\Users\\mb\\src\\gh\\omnisharp-roslyn\\src\\OmniSharp.Cake\\CakeProjectSystem.cs:line 121
```

**Comment by mholo65** [comment]
cc @gep13 @patriksvensson

**Comment by devlead** [comment]
Interesting:
`cake shimgen-help` will give you target path.

Guess one could check `"$env:ChocolateyInstall\lib\cake.portable\"`

**Comment by ymartin59** [comment]
Thanks. This explains why IntelliSense does not work... I would say it requires a fix in https://github.com/cake-build/bakery/pull/109/files after https://github.com/cake-build/bakery/issues/108
Also related to issue: #79

**Comment by ymartin59** [comment]
There is no configuration to divert `Cake.Core.Dll` autodetection. It may be interesting.
Or even better, grab target location from `cake shimgen-noop`

**Comment by ymartin59** [comment]
As an immediate work-around, append `C:\ProgramData\chocolatey\lib\cake.portable` to System PATH variable before `C:\ProgramData\chocolatey\bin\`... (do not add it to User profile PATH as it has less priority)

**Comment by devlead** [comment]
Now fixed when Cake.Core/Common ships with Bakery
