### ISSUE TITLE
Search for dotnet-cake in ~/.dotnet/tools/ additionally to PATH

### ISSUE THREAD

**Issue by nils-a** [cake-build/bakery#125]
As in https://github.com/cake-build/cake-rider/issues/78, [sometimes](https://github.com/cake-build/cake/discussions/3171) (seemingly on macs) the `$HOME/.dotnet/tools/` (`%USERPROFILE%\.dotnet\tools\`) is not in `PATH`.
We should, when resolving `dotnet-cake[.exe]`, check those folders additionally to `PATH`.

**Comment by bjorkstromm** [comment]
If anyone wants to take a stab at this. Relevant code is here:
https://github.com/cake-build/bakery/blob/develop/src/Cake.Scripting/CodeGen/CakeScriptGenerator.cs#L227

IMO we should also reorder the order that these are resolved in. First local (tool path), then Global Tool, then Cake.exe.. We could also consider ship Cake.Common with Bakery and use "built-in" Cake.Core + Cake.Common (preferably v1) as fallback.

**Comment by gep13** [comment]
@nils-a I have marked this as a bug, and assigned to the 0.5.2 milestone.  Does this make sense?

@bjorkstromm are you in a position to do a release of bakery, or would you like some help in this regard?

**Comment by bjorkstromm** [comment]
@gep13! Great! Not currently in position to do a release, might be able later. If you have time, please go ahead. It's using Cake.Recipe, so you know the process by heart 😄
