### ISSUE TITLE
0.6.0 Omnisharp Parsing Errors

### ISSUE THREAD

**Issue by rmbrunet** [cake-build/bakery#127]
Hello, seeing the following problem(s):

1.- Created brand new console application
2.- Initialized CakeBuild (tool-manifest, etc.)
3.- Added sample cake.build. Verified that it works.
3.- Installed Cake.Bakery using the VS Code Command option (Cake install enable intellisense support).  Got an errors in the OmniSharp log. No intellisesense. Here is the Omnisharp log:

Starting OmniSharp server at 3/6/2021, 8:27:25 AM
    Target: c:\Users\username\Source\Repos\CakeTest\CakeTest.sln

OmniSharp server started.
    Path: c:\Users\username\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.6\OmniSharp.exe
    PID: 8360

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2019 16.9.31025.194 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
            2: StandAlone 16.8.0 - "c:\Users\username\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.6\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2019 16.9.31025.194 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\username\Source\Repos\CakeTest'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Found 1 Cake files.
[info]: OmniSharp.Cake.Services.CakeScriptService
        Using Cake.Bakery at c:\Users\username\Source\Repos\CakeTest\tools\Cake.Bakery\tools\Cake.Bakery.exe
[fail]: OmniSharp.Cake.CakeProjectSystem
        c:\Users\username\Source\Repos\CakeTest\build.cake will be ignored due to an following error
System.IO.FileNotFoundException: Cake is not installed. Path c:/Users/username/Source/Repos/CakeTest/tools/Cake/Cake.Core.dll does not exist.
   at OmniSharp.Cake.CakeProjectSystem.GetProject(CakeScript cakeScript, String filePath) in D:\a\1\s\src\OmniSharp.Cake\CakeProjectSystem.cs:line 281
   at OmniSharp.Cake.CakeProjectSystem.AddCakeFile(String cakeFilePath) in D:\a\1\s\src\OmniSharp.Cake\CakeProjectSystem.cs:line 125
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'c:\Users\username\Source\Repos\CakeTest\CakeTest.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\username\Source\Repos\CakeTest\CakeTest\CakeTest.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\username\Source\Repos\CakeTest'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\username\Source\Repos\CakeTest' on host 1012.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\username\Source\Repos\CakeTest\CakeTest\CakeTest.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\username\Source\Repos\CakeTest\CakeTest\CakeTest.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\username\Source\Repos\CakeTest\CakeTest\CakeTest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: CakeTest
[warn]: OmniSharp.Stdio.Host
        ************ Request ************
{
  "Type": "request",
  "Seq": 226,
  "Command": "/v2/codestructure",
  "Arguments": {
    "FileName": "c:\\Users\\username\\Source\\Repos\\CakeTest\\build.cake"
  }
}
[fail]: OmniSharp.Stdio.Host
        ************  Response ************ 
{
  "Request_seq": 226,
  "Command": "/v2/codestructure",
  "Running": true,
  "Success": false,
  "Message": "\"System.NullReferenceException: Object reference not set to an instance of an object.\\r\\n   at OmniSharp.Cake.Extensions.ResponseExtensions.<TranslateAsync>d__7.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Cake\\\\Extensions\\\\ResponseExtensions.cs:line 153\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at OmniSharp.Cake.Services.RequestHandlers.CakeRequestHandler`2.<Handle>d__14.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at OmniSharp.Endpoint.EndpointHandler`2.<GetFirstNotEmptyResponseFromHandlers>d__19.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at OmniSharp.Endpoint.EndpointHandler`2.<HandleRequestForLanguage>d__20.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Host\\\\Endpoint\\\\EndpointHandler.cs:line 230\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at OmniSharp.Endpoint.EndpointHandler`2.<Process>d__16.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Host\\\\Endpoint\\\\EndpointHandler.cs:line 131\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at OmniSharp.Stdio.Host.<HandleRequest>d__13.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Stdio\\\\Host.cs:line 215\"",
  "Body": null,
  "Seq": 32,
  "Type": "response"
}
[warn]: OmniSharp.Stdio.Host
        ************ Request ************
{
  "Type": "request",
  "Seq": 229,
  "Command": "/v2/codestructure",
  "Arguments": {
    "FileName": "c:\\Users\\username\\Source\\Repos\\CakeTest\\build.cake"
  }
}
[fail]: OmniSharp.Stdio.Host
        ************  Response ************ 
{
  "Request_seq": 229,
  "Command": "/v2/codestructure",
  "Running": true,
  "Success": false,
  "Message": "\"System.NullReferenceException: Object reference not set to an instance of an object.\\r\\n   at OmniSharp.Cake.Extensions.ResponseExtensions.<TranslateAsync>d__7.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Cake\\\\Extensions\\\\ResponseExtensions.cs:line 153\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at OmniSharp.Cake.Services.RequestHandlers.CakeRequestHandler`2.<Handle>d__14.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at OmniSharp.Endpoint.EndpointHandler`2.<GetFirstNotEmptyResponseFromHandlers>d__19.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at OmniSharp.Endpoint.EndpointHandler`2.<HandleRequestForLanguage>d__20.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Host\\\\Endpoint\\\\EndpointHandler.cs:line 230\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at OmniSharp.Endpoint.EndpointHandler`2.<Process>d__16.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Host\\\\Endpoint\\\\EndpointHandler.cs:line 131\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at OmniSharp.Stdio.Host.<HandleRequest>d__13.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Stdio\\\\Host.cs:line 215\"",
  "Body": null,
  "Seq": 37,
  "Type": "response"
}

**Comment by augustoproiete** [comment]
> 2.- Initialized CakeBuild (tool-manifest, etc.)

Currently the IntelliSense requires the Cake .NET tool to be installed as a **global tool**. Based on your comment, it looks like you installed the Cake .NET tool as a **local tool** via the manifest (which is fine - and what's recommended for building your projects -, but specifically for the IntelliSense it's not used)... So in your case you need to have both local and global tool installed.

Could you please try to install Cake as a global tool:

```powershell
dotnet tool install --global Cake.Tool --version 1.1.0
```

And then restart OmniSharp (or restart VSCode)?

![image](https://user-images.githubusercontent.com/177608/110215307-65468980-7e7f-11eb-9634-ed96c63b4503.png)

---

The above works for most people and it's the standard way of getting the IntelliSense support. There are an edge case that seem to affect some people where the .NET Tool might be installed globally but for some reason it doesn't seem to be in the `%PATH%` within VSCode, which causes our extension not to be able to find it - it's something we're still working to fix.

The (_temporary_) workaround in this case is to install the Cake .NET Core CLR runner via VS Code, as described in this discussion: [Visual Studio Code Intellisense doesn't work on macOS](https://github.com/cake-build/cake/discussions/3171#discussioncomment-382529).

**Comment by rmbrunet** [comment]
Hi Augusto, 

The first -normal- option didn't work ___but the temporary work around did___. I verified that the global tool was visible from the terminal (deleting the tool-manifest). But it seems that was not visible from the Cake.Bakery tool: it was looking for it under the local tools folder.

If I can be of any help providing information about my configuration, or testing something let me know.

REgards,

R.

**Comment by augustoproiete** [comment]
@rmbrunet Great to hear that at least you have a workaround to get the IntelliSense working!

If you have a chance, could you try to clone this repo: https://github.com/augustoproiete-repros/repro-omnisharp-parsing-errors-cake-bakery and and repeat the normal steps, see if you get the same errors with OmniSharp, and post the full log here?

Also, could you please post the contents of `dotnet --info` running from the folder where you clone the repo above?

**Comment by rmbrunet** [comment]
Hello All,

Seeing that @nils-a probably already fixed whatever was happening... @augustoproiete,  will do what you asked anyway in case is useful. 

Ffter cloning the repo and repeating the "normal" process the result is still bad - but different than before: I see no errors in the OmniSharp Log (inlcuded below) but a lot of  PROBLEMS of the type:

{
	"resource": "/B3437BF2-8AE3-4281-8726-B926BB9DF75D",
	"owner": "csharp",
	"code": "CS0012",
	"severity": 8,
	"message": **"The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. [build.cake]"**,
	"source": "csharp",
	"startLineNumber": 25,
	"startColumn": 40,
	"endLineNumber": 25,
	"endColumn": 51
}

dotnet --info attached at the end.

**Installing the Debug Dependencies did fix the problems!**


R.


===================================================

This is the OmniSharp log:

Starting OmniSharp server at 3/7/2021, 7:16:42 AM
    Target: c:\Users\rmbrunet\Desktop\CaheBakeryTest\repro-omnisharp-parsing-errors-cake-bakery

OmniSharp server started.
    Path: c:\Users\rmbrunet\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.6\OmniSharp.exe
    PID: 11720

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2019 16.9.31025.194 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
            2: StandAlone 16.8.0 - "c:\Users\rmbrunet\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.6\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2019 16.9.31025.194 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\rmbrunet\Desktop\CaheBakeryTest\repro-omnisharp-parsing-errors-cake-bakery'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Found 1 Cake files.
[info]: OmniSharp.Cake.Services.CakeScriptService
        Using Cake.Bakery at c:\Users\rmbrunet\Desktop\CaheBakeryTest\repro-omnisharp-parsing-errors-cake-bakery\./tools\Cake.Bakery\tools\Cake.Bakery.exe
[info]: OmniSharp.Cake.CakeProjectSystem
        Added Cake project 'c:\Users\rmbrunet\Desktop\CaheBakeryTest\repro-omnisharp-parsing-errors-cake-bakery\build.cake' to the workspace.
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\rmbrunet\Desktop\CaheBakeryTest\repro-omnisharp-parsing-errors-cake-bakery'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\rmbrunet\Desktop\CaheBakeryTest\repro-omnisharp-parsing-errors-cake-bakery\ConsoleApp\ConsoleApp\ConsoleApp.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\rmbrunet\Desktop\CaheBakeryTest\repro-omnisharp-parsing-errors-cake-bakery'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\rmbrunet\Desktop\CaheBakeryTest\repro-omnisharp-parsing-errors-cake-bakery' on host 4552.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\rmbrunet\Desktop\CaheBakeryTest\repro-omnisharp-parsing-errors-cake-bakery\ConsoleApp\ConsoleApp\ConsoleApp.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\rmbrunet\Desktop\CaheBakeryTest\repro-omnisharp-parsing-errors-cake-bakery\ConsoleApp\ConsoleApp\ConsoleApp.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\rmbrunet\Desktop\CaheBakeryTest\repro-omnisharp-parsing-errors-cake-bakery\ConsoleApp\ConsoleApp\ConsoleApp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: ConsoleApp
Received response for /v2/getcodeactions but could not find request.

===============================================================

And this is dotnet --info

dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.200
 Commit:    70b3e65d53

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.200\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  1.0.0-preview2-003121 [C:\Program Files\dotnet\sdk]
  1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
  1.0.0 [C:\Program Files\dotnet\sdk]
  1.0.3 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.100 [C:\Program Files\dotnet\sdk]
  2.1.102 [C:\Program Files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300-rc1-008673 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.617 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.2.100 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]
  2.2.204 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]
  5.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by rmbrunet** [comment]
It seems the issue wasn't completely resolved with 0.6.1. 

1. Created new folder.
2. Created tool-manifest
3. Installed Cake.Tool
4. Installed sample cake.build
5. Tested dotnet cake in the terminal. All good. No intellisense yet.
6.  Enabled intellisense. Re-started OmniSharp. Intellisense works but now there are numerous errors of the type "The Type <Type> is defined in an assemble that is not referenced.  
![image](https://user-images.githubusercontent.com/2124799/110243401-36382280-7f28-11eb-90ba-f7817f5b115c.png)
7. Installing Debug dependencies fixed the issue.

Regards,

R.

**Comment by gep13** [comment]
Can you clarify what you did here:

> Installing Debug dependencies fixed the issue.

There are two options when you choose this command in Visual Studio Code.  Thanks

**Comment by rmbrunet** [comment]
This one

![image](https://user-images.githubusercontent.com/2124799/110244180-849af080-7f2b-11eb-8beb-9d492c111205.png)

This is how the folder lokks

![image](https://user-images.githubusercontent.com/2124799/110244213-a5fbdc80-7f2b-11eb-83df-939c1270d5de.png)

**Comment by augustoproiete** [comment]
Thanks @rmbrunet I can repro the `Type is defined in an assemble that is not referenced` error. Tracking on https://github.com/cake-build/bakery/issues/129

**Comment by augustoproiete** [comment]
@rmbrunet Cake.Bakery 0.6.2 should fix the `Type is defined in an assemble that is not referenced` error you saw reported above. Please let us know if you find anything else.

**Comment by rmbrunet** [comment]
Thanks @augustoproiete! I did test 0.6.2 all worked fine.
