### ISSUE TITLE
Intellisense issues

### ISSUE THREAD

**Issue by gitfool** [cake-build/bakery#131]
I thought I'd take another look at Cake intellisense in Visual Studio Code. My setup:
* [`Cake.Tool`](https://github.com/cake-build/cake) 1.1.0 installed as a global tool
* [`Cake.Bakery`](https://github.com/cake-build/bakery) 0.6.2 installed using chocolatey
* [`Cake.Dungeon`](https://github.com/gitfool/Cake.Dungeon) source

Everything seems to initialize okay when I open the repo root in Visual Studio Code:
```log
Starting OmniSharp server at 3/15/2021, 2:41:39 PM
    Target: d:\Devel\Repos\gitfool\Cake.Dungeon\Cake.Dungeon.sln

OmniSharp server started.
    Path: c:\Users\sfausett\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.6\OmniSharp.exe
    PID: 10676

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 4 MSBuild instance(s)
            1: Visual Studio Build Tools 2017 15.9.28307.1440 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
            2: Visual Studio Enterprise 2019 16.9.31105.61 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin"
            3: Visual Studio Enterprise 2019 16.10.31025.218 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin"
            4: StandAlone 16.8.0 - "c:\Users\sfausett\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.6\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Enterprise 2019 16.10.31025.218 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'd:\Devel\Repos\gitfool\Cake.Dungeon'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Found 13 Cake files.
[info]: OmniSharp.Cake.Services.CakeScriptService
        Using Cake.Bakery at C:\ProgramData\chocolatey\bin\Cake.Bakery.exe
[info]: OmniSharp.Cake.CakeProjectSystem
        Added Cake project 'd:\Devel\Repos\gitfool\Cake.Dungeon\build.cake' to the workspace.
[info]: OmniSharp.Cake.CakeProjectSystem
        Added Cake project 'd:\Devel\Repos\gitfool\Cake.Dungeon\scripts\bootstrap.cake' to the workspace.
[info]: OmniSharp.Cake.CakeProjectSystem
        Added Cake project 'd:\Devel\Repos\gitfool\Cake.Dungeon\scripts\builder.cake' to the workspace.
[info]: OmniSharp.Cake.CakeProjectSystem
        Added Cake project 'd:\Devel\Repos\gitfool\Cake.Dungeon\scripts\credentials.cake' to the workspace.
[info]: OmniSharp.Cake.CakeProjectSystem
        Added Cake project 'd:\Devel\Repos\gitfool\Cake.Dungeon\scripts\docker.cake' to the workspace.
[info]: OmniSharp.Cake.CakeProjectSystem
        Added Cake project 'd:\Devel\Repos\gitfool\Cake.Dungeon\scripts\environment.cake' to the workspace.
[info]: OmniSharp.Cake.CakeProjectSystem
        Added Cake project 'd:\Devel\Repos\gitfool\Cake.Dungeon\scripts\extensions.cake' to the workspace.
[info]: OmniSharp.Cake.CakeProjectSystem
        Added Cake project 'd:\Devel\Repos\gitfool\Cake.Dungeon\scripts\parameters.cake' to the workspace.
[info]: OmniSharp.Cake.CakeProjectSystem
        Added Cake project 'd:\Devel\Repos\gitfool\Cake.Dungeon\scripts\paths.cake' to the workspace.
[info]: OmniSharp.Cake.CakeProjectSystem
        Added Cake project 'd:\Devel\Repos\gitfool\Cake.Dungeon\scripts\patterns.cake' to the workspace.
[info]: OmniSharp.Cake.CakeProjectSystem
        Added Cake project 'd:\Devel\Repos\gitfool\Cake.Dungeon\scripts\tasks.cake' to the workspace.
[info]: OmniSharp.Cake.CakeProjectSystem
        Added Cake project 'd:\Devel\Repos\gitfool\Cake.Dungeon\scripts\toolsettings.cake' to the workspace.
[info]: OmniSharp.Cake.CakeProjectSystem
        Added Cake project 'd:\Devel\Repos\gitfool\Cake.Dungeon\scripts\version.cake' to the workspace.
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'd:\Devel\Repos\gitfool\Cake.Dungeon\Cake.Dungeon.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\Devel\Repos\gitfool\Cake.Dungeon\Cake.Dungeon.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'd:\Devel\Repos\gitfool\Cake.Dungeon'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'd:\Devel\Repos\gitfool\Cake.Dungeon' on host 3892.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\Devel\Repos\gitfool\Cake.Dungeon\Cake.Dungeon.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'd:\Devel\Repos\gitfool\Cake.Dungeon\Cake.Dungeon.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'd:\Devel\Repos\gitfool\Cake.Dungeon\Cake.Dungeon.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Cake.Dungeon
```
But when I go to edit some of the cake script files I see squiggles in the editor and errors in the log like:
* [bootstrap.log](https://github.com/cake-build/bakery/files/6138277/bootstrap.log)
* [tasks.log](https://github.com/cake-build/bakery/files/6138282/tasks.log)

![image](https://user-images.githubusercontent.com/750121/111093743-8b1a0f80-859e-11eb-82f3-00dc27ad685c.png)

Is there something I'm doing wrong or am I breaking any rules by using multiple cake files etc?

**Comment by nils-a** [comment]
I somehow have the feeling this is a limitation for multi-cake-file-projects in bakery.
@bjorkstromm did you say something like that sometime?

**Comment by bjorkstromm** [comment]
In the screenshot, do you load (via `#load`) the file where `Build` is defined?

**Comment by nils-a** [comment]
That's in `scripts/bootstap.cake`

**Comment by bjorkstromm** [comment]
Yes, that must be loaded from `tasks.cake` then. All dependencies must be loaded in a script in order for compilation to find it. 

You'd get the exact same compilation errors if you'd use `tasks.cake` as entry point when running cake. E.g. 
```
dotnet cake scripts/tasks.cake
```

**Comment by gep13** [comment]
All the scripts are loaded from the build.cake file here:

https://github.com/gitfool/Cake.Dungeon/blob/master/build.cake#L1

**Comment by gep13** [comment]
Once being used on an actual "build" I am assuming that Cake.Dungeon would be loaded using the `load` preprocessor that references a NuGet package, similar to how Cake.Recipe works.

**Comment by bjorkstromm** [comment]
> All the scripts are loaded from the build.cake file here:
> 
> https://github.com/gitfool/Cake.Dungeon/blob/master/build.cake#L1

Yes, but then the entry point is `build.cake`. In the attached screenshot, the opened file is `scripts/tasks.cake`. The compiler can not know about dependencies that are not loaded, therefore the compiler errors are shown.

**Comment by gep13** [comment]
When you say entry point, can you confirm what you mean? Is it that this is the file that is open?

**Comment by gitfool** [comment]
Basically there are multiple script files that all come together:
* Loaded in [build.cake](https://github.com/gitfool/Cake.Dungeon/blob/60cac2a682d92b833db1f89c79d02afdc8c0f913/build.cake#L1)
* Definition of `Builder` class in [builder.cake](https://github.com/gitfool/Cake.Dungeon/blob/60cac2a682d92b833db1f89c79d02afdc8c0f913/scripts/builder.cake#L1)
* Instantiation of `Builder` class in [bootstrap.cake](https://github.com/gitfool/Cake.Dungeon/blob/60cac2a682d92b833db1f89c79d02afdc8c0f913/scripts/bootstrap.cake#L8)
* Extensions to `Builder` class in [extensions.cake](https://github.com/gitfool/Cake.Dungeon/blob/60cac2a682d92b833db1f89c79d02afdc8c0f913/scripts/extensions.cake#L15)
* etc

**Comment by bjorkstromm** [comment]
> When you say entry point, can you confirm what you mean? Is it that this is the file that is open?

Yes, the file that is open.

**Comment by gep13** [comment]
So, should this work if the build.cake file is opened and Omnisharp restarted?

**Comment by bjorkstromm** [comment]
> So, should this work if the build.cake file is opened and Omnisharp restarted?

If `build.cake` is opened, yes the intellisense should work for that file, and no red squigglies under the `Build` symbol. No need to restart OmniSharp to get that working.

In order to get it working for the file in the attached screenshot, that file MUST load it's dependencies. E.g. add

```
#load bootstrap.cake
```

To the top of that file.

Does this make sense? As I mentioned earlier, when you have opened `tasks.cake`, in that current context, the file dependencies (where `Build` is instantiated) is not loaded, therefore the compiler can't possibly know about this symbol.

**Comment by gitfool** [comment]
Thanks, @bjorkstromm! I [rearranged the deck chairs](https://github.com/gitfool/Cake.Dungeon/commit/f957c2f3d3ffa21a9a02e6f1a65a9b25f3b56d10) and now I'm only seeing the following intellisense issues in [tasks.cake#L203](https://github.com/gitfool/Cake.Dungeon/blob/f957c2f3d3ffa21a9a02e6f1a65a9b25f3b56d10/scripts/tasks.cake#L203):

![image](https://user-images.githubusercontent.com/750121/112769555-3e463680-907e-11eb-9310-c14a883d56ab.png)

and [tasks.cake#L357](https://github.com/gitfool/Cake.Dungeon/blob/f957c2f3d3ffa21a9a02e6f1a65a9b25f3b56d10/scripts/tasks.cake#L357):

![image](https://user-images.githubusercontent.com/750121/112769741-16a39e00-907f-11eb-9d6c-d60daa21aa33.png)

Is there configuration I need to use to get OmniSharp to recognize the latest C# language features?

**Comment by gitfool** [comment]
AFAICT, OmniSharp should already be using the latest C# language version.

The first error, `The non-generic method 'Enum.Parse(Type, string)' cannot be used with type arguments [...] csharp(CS0308)`, refers to [CS0308](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0308) for the [Enum.Parse\<TEnum\>(String)](https://docs.microsoft.com/en-us/dotnet/api/system.enum.parse#System_Enum_Parse__1_System_String_) method, and seems to be because this method is only available for .NET Core 2.0 and later.

The other errors, `Predefined type 'System.Index' is not defined or imported [...] csharp(CS0518)` and `Predefined type 'System.Range' is not defined or imported [...] csharp(CS0518)`, refer to [CS0518](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0518) for the [Index](https://docs.microsoft.com/en-us/dotnet/api/system.index) and [Range](https://docs.microsoft.com/en-us/dotnet/api/system.range) types introduced in C# 8.0 [ranges](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/ranges), and seem to be because these types are only available for .NET Core 3.0 and later.

Is this a configuration issue? What am I missing?

**Comment by bjorkstromm** [comment]
Interesting. IIRC, we use `latest` as lang version for Cake, and it's not configurable. 

I need to test this and see. It might be that script is (for some reason) tarheting NetFx insteand of NetCore (or NET5). If you set OmniSharp log to verbose (trace), you should see the path for Cake.Core and Cake.Commom it's using.

**Comment by gitfool** [comment]
Looks like `Cake.Core` is being loaded from [`Cake.Tool`](https://github.com/cake-build/cake) 1.1.0 installed as a global tool: [OmniSharp.log](https://github.com/cake-build/bakery/files/6253363/OmniSharp.log)

**Comment by gitfool** [comment]
@bjorkstromm I guess you haven't had a chance to look into this? Let me know if I can help...

**Comment by bjorkstromm** [comment]
> @bjorkstromm I guess you haven't had a chance to look into this? Let me know if I can help...

Correct (but I also forgot about this 🙈). But I *think* we somehow need to change the target framework to work around this. It might need some work to accomplish that however.

On the top of my head, I'm unsure where to start, but I *think* OmniSharp.Script supports changing target framework, so that could give us some hints. We also need to modify Bakery side to resolve correct assemblies from Addins (and Cake) based on the selected TFM.

**Comment by gitfool** [comment]
Fixed in the latest `Cake.Bakery`. 🎉
