### ISSUE TITLE
Strong-name sign Abstractions and Transport

### ISSUE THREAD

**Issue by bjorkstromm** [cake-build/bakery#133]
Needed for https://github.com/OmniSharp/omnisharp-roslyn/pull/2143

**Comment by 333fred** [comment]
Hopefully we do have a workaround by using https://github.com/dsplaisted/strongnamer, but it would be good to have all dependencies _actually_ strong-name signed. Should help anyone else who runs into similar problems.

**Comment by gep13** [comment]
@333fred I have used this tool https://github.com/brutaldev/StrongNameSigner on the Chocolatey code base when we have needed to sign some dependencies that aren't strong named, and this has worked really well for us.

**Comment by 333fred** [comment]
> 
> 
> @333fred I have used this tool https://github.com/brutaldev/StrongNameSigner on the Chocolatey code base when we have needed to sign some dependencies that aren't strong named, and this has worked really well for us.

I tried that one first, actually. It didn't appear to work with recent versions of msbuild.

**Comment by gep13** [comment]
Hmm, this might be some fun in my immediate future then ☹️ Chocolatey is currently targeting older versions of MSBuild for backwards compatibility, which is likely why we haven't seen problems.
