### ISSUE TITLE
Reference to `System.Text.RegularExpressions` is missing

### ISSUE THREAD

**Issue by gitfool** [cake-build/bakery#148]
Similar to #147, only for `System.Text.RegularExpressions`, this now shows squiggles where it did not, before updating `Cake.Bakery`:

![image](https://user-images.githubusercontent.com/750121/141695907-a6335091-1e53-47c6-b076-4bccf0f3c9fd.png)

Also, since `Cake.Bakery` is tied to the last stable version of `Cake`, the new `DotNet` aliases in `2.0.0-rc0001` show squiggles too.

**Comment by pascalberger** [comment]
Could we improve this by using [Basic.Reference.Assemblies](https://github.com/jaredpar/basic-reference-assemblies)?

**Comment by bjorkstromm** [comment]
Yes, we should definitively use that instead.
