### ISSUE TITLE
Create build scripts

### ISSUE THREAD

**Issue by mholo65** [cake-build/bakery#15]
Create build scripts

//cc @gep13

**Comment by gep13** [comment]
@mholo65 yip, this is on my list.  I am working on the assumption that if I get Cake.Recipe building .NET Core Solutions, then it should be a simple add to use Cake.Recipe to build this project.

**Comment by mholo65** [comment]
:+1:

**Comment by gep13** [comment]
Looks like, thanks to the amazing work of @AdmiringWorm, we are one step closer to maybe getting this out the door 😄

**Comment by gep13** [comment]
@mholo65 so I think we can close this one, right?

**Comment by mholo65** [comment]
@gep13 yep! Solved with CI issue!

**Comment by mholo65** [comment]
Solved by #27
