### ISSUE TITLE
`Uri` not found in `System` namespace

### ISSUE THREAD

**Issue by gitfool** [cake-build/bakery#152]
After upgrading to `Cake.Bakery` version `0.8.0`:

![image](https://user-images.githubusercontent.com/750121/143326938-f807fa34-6a4b-4551-a88f-76e95336f2de.png)

**Comment by gep13** [comment]
This is like playing whack-a-mole!

@devlead is it likely that this will be taken care of by your upstream addition into Cake and then we can pull that RC into bakey?

**Comment by devlead** [comment]
I'm taking a look if it's a quick fix or not.
Might be in both.

**Comment by devlead** [comment]
Might have a fix ready, will apply same to cake PR too.
![image](https://user-images.githubusercontent.com/1647294/143403727-24169bde-9e4f-46f7-bfc4-1188e8e50fcb.png)

**Comment by gep13** [comment]
@gitfool could you take the latest version for a spin and let us know how you get on?

**Comment by gitfool** [comment]
@gep13 All good now, except for new aliases in `Cake` version `2.0.0-rc0001`:

![image](https://user-images.githubusercontent.com/750121/143484771-a3495b46-3c0a-4e16-b1e2-2002607dd2bf.png)

I expect that these will go away post `Cake` version `2.0.0` when a followup `Cake.Bakery` version will reference that too.

**Comment by gep13** [comment]
Yes, that is correct.

We will let things settle a little bit here, and then we can ship another release of Bakery targeting the rc version, or we wait until 2.0.0 ships.
