### ISSUE TITLE
Omnisharp Errors on non CIL assemblies

### ISSUE THREAD

**Issue by devlead** [cake-build/bakery#166]
Thanks for pushing a fast update.
But unfortunately I still experience same issue, with the new release.

One note when testing this fix:
OmniSharp (seems) to cache some of the provided IntelliSense hints.
Looking at screen shot provided in PR, it seems that IntelliSense is working. This happens to me as well under following conditions (it may have happened under different conditions in case of that screen shot):

- Add #addin reference without _loaddependencies_
- Try intellisense, and it works correctly
- Add _loaddependencies_ parameter to #addin directive, and intellisense keeps working

But now in OmniSharp log I get logged following:

> [fail]: OmniSharp.Stdio.Host
>         ************  Response (92.0336ms) ************ 
> {
>   "Request_seq": 250,
>   "Command": "/updatebuffer",
>   "Running": true,
>   "Success": false,
>   "Message": "\"System.BadImageFormatException: PE image doesn't contain managed metadata.\\r\\n   at Microsoft.CodeAnalysis.PEModule.InitializeMetadataReader()\\r\\n   at Microsoft.CodeAnalysis.PEModule.get_MetadataReader()\\r\\n   at Microsoft.CodeAnalysis.PEAssembly..ctor(AssemblyMetadata owner, ImmutableArray`1 modules)\\r\\n   at Microsoft.CodeAnalysis.AssemblyMetadata.GetOrCreateData()\\r\\n   at Microsoft.CodeAnalysis.AssemblyMetadata.GetModules()\\r\\n   at OmniSharp.Services.MetadataFileReferenceCache.GetMetadataReference(String filePath) in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Roslyn\\\\Services\\\\MetadataFileReferenceCache.cs:line 49\\r\\n   at OmniSharp.Cake.CakeProjectSystem.<GetMetadataReferences>d__39.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Cake\\\\CakeProjectSystem.cs:line 328\\r\\n   at OmniSharp.Cake.CakeProjectSystem.ScriptReferencesChanged(Object sender, ReferencesChangedEventArgs e) in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Cake\\\\CakeProjectSystem.cs:line 212\\r\\n   at OmniSharp.Cake.Services.CakeScriptService.Generate(FileChange fileChange) in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Cake\\\\Services\\\\CakeScriptService.cs:line 99\\r\\n   at OmniSharp.Cake.Services.RequestHandlers.Buffer.UpdateBufferHandler.<Handle>d__3.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Cake\\\\Services\\\\RequestHandlers\\\\Buffer\\\\UpdateBufferHandler.cs:line 60\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at OmniSharp.Endpoint.EndpointHandler`2.<GetFirstNotEmptyResponseFromHandlers>d__19.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at OmniSharp.Endpoint.EndpointHandler`2.<HandleRequestForLanguage>d__20.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Host\\\\Endpoint\\\\EndpointHandler.cs:line 230\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at OmniSharp.Endpoint.EndpointHandler`2.<Process>d__16.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Host\\\\Endpoint\\\\EndpointHandler.cs:line 131\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at OmniSharp.Stdio.Host.<HandleRequest>d__14.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Stdio\\\\Host.cs:line 218\"",
>   "Body": null,
>   "Seq": 269,
>   "Type": "response"
> }

Software I used:
VS Code 1.63.0
OmniSharp 1.37.17
Cake.Bakery 0.91 - This I verified multiple times. Did not believe result, so I also manually downloaded release ZIP and copied over. One interesting thing (for me), was that Cake.Bakery.exe is not binary identical between .nupkg and .zip. And also that in Details tab of File properties it says that version of Cake.Bakery.exe is 1.0.0. I believe this part you knew about

![image](https://user-images.githubusercontent.com/80263149/145694449-cb255270-11b1-46c8-a708-2aae65e1e7eb.png)

_Originally posted by @nikola-nignite in https://github.com/cake-build/bakery/issues/163#issuecomment-991802380_

**Comment by nikola-nignite** [comment]
I must be doing something wrong now, because I experience same issue with basic script :(
Without `loaddependencies`, intellisense works correctly.

This time I don't see anything specific to this being logged. I do get logged occasional `NullReferenceException`, but this also happens when there is no `loaddependencies` enabled.

I'd attempt to be more useful, but I spend more time than I hoped looking into logging, and I wasn't able to make my own build of Omnisharp work correctly with VS Code so that I can debug :(

![image](https://user-images.githubusercontent.com/80263149/145726694-a4d58494-b523-4522-89f5-d2bec53f29bd.png)

![image](https://user-images.githubusercontent.com/80263149/145726816-8a283379-6f78-49de-8a1c-3ab11f301a80.png)
