### ISSUE TITLE
Push to MyGet

### ISSUE THREAD

**Issue by mholo65** [cake-build/bakery#18]
- [ ] Push `Bakery.exe` as tool
- [ ] Push `Cake.Scripting.Transport` as library

**Comment by mholo65** [comment]
ping @gep13

**Comment by gep13** [comment]
@mholo65  Yip, this should be possible through the integration of Cake.Recipe.

**Comment by gep13** [comment]
This has now been completed, and the environment variables added into AppVeyor configuration.
