### ISSUE TITLE
Move test from src to test

### ISSUE THREAD

**Issue by mholo65** [cake-build/bakery#20]

**Comment by gep13** [comment]
@mholo65 what is the thinking behind this?

**Comment by mholo65** [comment]
@patriksvensson suggested we move Tests out from `src` to `test` in root. I'm all in for that!

**Comment by gep13** [comment]
Cake.Recipe, as it currently stands, assumes that all projects, including Tests, live under a single `src`/`source` folder.

That is not to say that Cake.Recipe can't be changed to accommodate, but just wanted to point this out.

**Comment by mholo65** [comment]
@gep13 ok, lets follow `Cake.Recipe` conventions then :+1:
