### ISSUE TITLE
Namespace missing from Usings list

### ISSUE THREAD

**Issue by mholo65** [cake-build/bakery#44]
Namespace missing from Usings list.

Tested with this simple script:
```csharp
#addin "Cake.Incubator"

var target = Argument("target", "Default");

Task("Default")
  .Does(() =>
{
  Information(new NUnit3Settings().Dump());
});

RunTarget(target);
```

But generates the below (actual). Reference generated by `Cake.exe` (expected).

Expected | Actual
-- | --
Cake.Common |  
Cake.Common.Build |  
Cake.Common.Build.AppVeyor | Cake.Common.Build.AppVeyor
Cake.Common.Build.AppVeyor.Data | Cake.Common.Build.AppVeyor.Data
Cake.Common.Build.Bamboo | Cake.Common.Build.Bamboo
Cake.Common.Build.Bamboo.Data | Cake.Common.Build.Bamboo.Data
Cake.Common.Build.BitbucketPipelines | Cake.Common.Build.BitbucketPipelines
Cake.Common.Build.BitbucketPipelines.Data | Cake.Common.Build.BitbucketPipelines.Data
Cake.Common.Build.Bitrise | Cake.Common.Build.Bitrise
Cake.Common.Build.Bitrise.Data | Cake.Common.Build.Bitrise.Data
Cake.Common.Build.ContinuaCI | Cake.Common.Build.ContinuaCI
Cake.Common.Build.ContinuaCI.Data | Cake.Common.Build.ContinuaCI.Data
Cake.Common.Build.GitLabCI | Cake.Common.Build.GitLabCI
Cake.Common.Build.GitLabCI.Data | Cake.Common.Build.GitLabCI.Data
Cake.Common.Build.GoCD | Cake.Common.Build.GoCD
Cake.Common.Build.GoCD.Data | Cake.Common.Build.GoCD.Data
Cake.Common.Build.Jenkins | Cake.Common.Build.Jenkins
Cake.Common.Build.Jenkins.Data | Cake.Common.Build.Jenkins.Data
Cake.Common.Build.MyGet | Cake.Common.Build.MyGet
Cake.Common.Build.TeamCity | Cake.Common.Build.TeamCity
Cake.Common.Build.TFBuild | Cake.Common.Build.TFBuild
Cake.Common.Build.TFBuild.Data | Cake.Common.Build.TFBuild.Data
Cake.Common.Build.TravisCI | Cake.Common.Build.TravisCI
Cake.Common.Build.TravisCI.Data | Cake.Common.Build.TravisCI.Data
Cake.Common.Diagnostics |  
Cake.Common.IO |  
Cake.Common.IO.Paths | Cake.Common.IO.Paths
Cake.Common.Net |  
Cake.Common.Security |  
Cake.Common.Solution |  
Cake.Common.Solution.Project |  
Cake.Common.Solution.Project.Properties |  
Cake.Common.Solution.Project.XmlDoc |  
Cake.Common.Text |  
Cake.Common.Tools |  
Cake.Common.Tools.Cake |  
Cake.Common.Tools.Chocolatey |  
Cake.Common.Tools.Chocolatey.ApiKey | Cake.Common.Tools.Chocolatey.ApiKey
Cake.Common.Tools.Chocolatey.Config | Cake.Common.Tools.Chocolatey.Config
Cake.Common.Tools.Chocolatey.Features | Cake.Common.Tools.Chocolatey.Features
Cake.Common.Tools.Chocolatey.Install | Cake.Common.Tools.Chocolatey.Install
Cake.Common.Tools.Chocolatey.New | Cake.Common.Tools.Chocolatey.New
Cake.Common.Tools.Chocolatey.Pack | Cake.Common.Tools.Chocolatey.Pack
Cake.Common.Tools.Chocolatey.Pin | Cake.Common.Tools.Chocolatey.Pin
Cake.Common.Tools.Chocolatey.Push | Cake.Common.Tools.Chocolatey.Push
Cake.Common.Tools.Chocolatey.Sources | Cake.Common.Tools.Chocolatey.Sources
Cake.Common.Tools.Chocolatey.Uninstall | Cake.Common.Tools.Chocolatey.Uninstall
Cake.Common.Tools.Chocolatey.Upgrade | Cake.Common.Tools.Chocolatey.Upgrade
Cake.Common.Tools.DotCover |  
Cake.Common.Tools.DotCover.Analyse | Cake.Common.Tools.DotCover.Analyse
Cake.Common.Tools.DotCover.Cover | Cake.Common.Tools.DotCover.Cover
Cake.Common.Tools.DotCover.Merge | Cake.Common.Tools.DotCover.Merge
Cake.Common.Tools.DotCover.Report | Cake.Common.Tools.DotCover.Report
Cake.Common.Tools.DotNetCore |  
Cake.Common.Tools.DotNetCore.Build | Cake.Common.Tools.DotNetCore.Build
Cake.Common.Tools.DotNetCore.Execute | Cake.Common.Tools.DotNetCore.Execute
Cake.Common.Tools.DotNetCore.Pack | Cake.Common.Tools.DotNetCore.Pack
Cake.Common.Tools.DotNetCore.Publish | Cake.Common.Tools.DotNetCore.Publish
Cake.Common.Tools.DotNetCore.Restore | Cake.Common.Tools.DotNetCore.Restore
Cake.Common.Tools.DotNetCore.Run | Cake.Common.Tools.DotNetCore.Run
Cake.Common.Tools.DotNetCore.Test | Cake.Common.Tools.DotNetCore.Test
Cake.Common.Tools.DupFinder |  
Cake.Common.Tools.Fixie |  
Cake.Common.Tools.GitLink |  
Cake.Common.Tools.GitReleaseManager |  
Cake.Common.Tools.GitReleaseManager.AddAssets | Cake.Common.Tools.GitReleaseManager.AddAssets
Cake.Common.Tools.GitReleaseManager.Close | Cake.Common.Tools.GitReleaseManager.Close
Cake.Common.Tools.GitReleaseManager.Create | Cake.Common.Tools.GitReleaseManager.Create
Cake.Common.Tools.GitReleaseManager.Export | Cake.Common.Tools.GitReleaseManager.Export
Cake.Common.Tools.GitReleaseManager.Publish | Cake.Common.Tools.GitReleaseManager.Publish
Cake.Common.Tools.GitReleaseNotes |  
Cake.Common.Tools.GitVersion |  
Cake.Common.Tools.ILMerge |  
Cake.Common.Tools.ILRepack |  
Cake.Common.Tools.InnoSetup |  
Cake.Common.Tools.InspectCode |  
Cake.Common.Tools.MSBuild |  
Cake.Common.Tools.MSTest |  
Cake.Common.Tools.NSIS |  
Cake.Common.Tools.NuGet |  
Cake.Common.Tools.NuGet.Add | Cake.Common.Tools.NuGet.Add
Cake.Common.Tools.NuGet.Init | Cake.Common.Tools.NuGet.Init
Cake.Common.Tools.NuGet.Install | Cake.Common.Tools.NuGet.Install
Cake.Common.Tools.NuGet.Pack | Cake.Common.Tools.NuGet.Pack
Cake.Common.Tools.NuGet.Push | Cake.Common.Tools.NuGet.Push
Cake.Common.Tools.NuGet.Restore | Cake.Common.Tools.NuGet.Restore
Cake.Common.Tools.NuGet.SetApiKey | Cake.Common.Tools.NuGet.SetApiKey
Cake.Common.Tools.NuGet.SetProxy | Cake.Common.Tools.NuGet.SetProxy
Cake.Common.Tools.NuGet.Sources | Cake.Common.Tools.NuGet.Sources
Cake.Common.Tools.NuGet.Update | Cake.Common.Tools.NuGet.Update
Cake.Common.Tools.NUnit |  
Cake.Common.Tools.OctopusDeploy |  
Cake.Common.Tools.OpenCover |  
Cake.Common.Tools.ReportGenerator |  
Cake.Common.Tools.ReportUnit |  
Cake.Common.Tools.Roundhouse |  
Cake.Common.Tools.SignTool |  
Cake.Common.Tools.SpecFlow |  
Cake.Common.Tools.SpecFlow.StepDefinitionReport | Cake.Common.Tools.SpecFlow.StepDefinitionReport
Cake.Common.Tools.SpecFlow.TestExecutionReport | Cake.Common.Tools.SpecFlow.TestExecutionReport
Cake.Common.Tools.TextTransform |  
Cake.Common.Tools.WiX | Cake.Common.Tools.WiX.Heat
Cake.Common.Tools.WiX.Heat |  
Cake.Common.Tools.VSTest |  
Cake.Common.Tools.VSWhere |  
Cake.Common.Tools.VSWhere.All | Cake.Common.Tools.VSWhere.All
Cake.Common.Tools.VSWhere.Latest | Cake.Common.Tools.VSWhere.Latest
Cake.Common.Tools.VSWhere.Legacy | Cake.Common.Tools.VSWhere.Legacy
Cake.Common.Tools.VSWhere.Product | Cake.Common.Tools.VSWhere.Product
Cake.Common.Tools.XBuild |  
Cake.Common.Tools.XUnit |  
Cake.Common.Xml |  
Cake.Core | Cake.Core
Cake.Core.Diagnostics | Cake.Core.Diagnostics
Cake.Core.IO | Cake.Core.IO
Cake.Core.Scripting | Cake.Core.Scripting
Cake.Incubator |  
System | System
System.Collections.Generic | System.Collections.Generic
System.IO | System.IO
System.Linq | System.Linq
System.Text | System.Text
System.Threading.Tasks | System.Threading.Tasks

**Comment by mholo65** [comment]
@devlead @patriksvensson do you see any pattern why these namespaces are missing from the returned list of namespaces to import?

**Comment by devlead** [comment]
Could it be the implicit property / method alias imports?

**Comment by patriksvensson** [comment]
Hmmm, Perhaps we haven't implemented namespace attributes in the bakery based generator. I can take a look at this tonight.

**Comment by mholo65** [comment]
It seems to import those marked with  `CakeNamespaceImport`? But doesn't automatically import a namespace even tough it contains Method/Property alias

**Comment by patriksvensson** [comment]
The problem is here: https://github.com/cake-build/bakery/blob/develop/src/Cake.Scripting/CodeGen/CakeScriptAliasFinder.cs#L139

We need to add namespaces for the types as well.
