### ISSUE TITLE
How To Use

### ISSUE THREAD

**Issue by Meir017** [cake-build/bakery#67]
I've been following this repository for over a month now but I'm not totally sure what it's supposed to do.
Seems to me to have something to do with intellisense for case scripts but I'm not sure.

Any plans on adding a section on how to use in the readme?

**Comment by devlead** [comment]
Bakery is still work in process and still undergoing major refactoring, but when we've baked things and shipped something it's on the agenda to update readme and provide documentation, 

Very simplified what it does. basically it replicates the code generation Cake does for its DSL, i.e. provides functionality needed for preprocessor directives, mapping script lines to generated lines, reflects over addins, namespace imports etc.

Which will provide i.e. editors like VSCode (via OmniSharp) with the meta data it needs to provide intellisense. But it's potential could be way beyond that.

**Comment by fschwiet** [comment]
In the troubleshooting section is says to check omnistar logs: https://cakebuild.net/blog/2017/11/intellisense-vscode

I don't know what an omnistar is, I can google instructions on turning on logging but I'm not sure I've found the right thing.  Can someone point me in the right direction?

**Comment by SIkebe** [comment]
@fschwiet I can't find omnistar. Isn't it `omnisharp`?

**Comment by gep13** [comment]
@fschwiet what is being referred to is this:

![image](https://user-images.githubusercontent.com/1271146/33797101-c45502ce-dcf9-11e7-9896-0fe023c999a5.png)

Omnisharp runs inside VSCode, and if there are any problems with it, they should be written to the Output Log.

**Comment by patriksvensson** [comment]
Where do you see `OmniStar` in that blog post?

**Comment by fschwiet** [comment]
I wrote omnistar by mistake, I meant to reference Omnisharp.  Thanks for recognziing what I meant to ask anyhow.

**Comment by pascalberger** [comment]
Instructions how to enable IntelliSense in Visual Studio Code is now available at https://cakebuild.net/docs/editors/vscode/intellisense.
