### ISSUE TITLE
Intellisense not working for .cake files in subfolders

### ISSUE THREAD

**Issue by mholo65** [cake-build/bakery#79]
Need to investigate what's causing this..

**Comment by Insire** [comment]
Thanks for opening this.

Here are some repro steps for my own [project(Maple)](https://github.com/Insire/Maple).
- Clone it
- Open its root folder with vs code
- Install Intellisense support
- move the new .\tools\Cake.Bakery\ folder to .\Cake\tools\ 
- Update cake.config in .\Cake\ with the following values
```
[Paths]
Tools=./Cake/tools
Addins=./Cake/tools/Addins
Modules=./Cake/tools/Modules
```

- restart vs code
-> after restart and reopen of the workspace, it should show intellisense for .\Cake\build.cake
--> sadly it does not

If you are interested in any further information, please let me know

**Comment by mholo65** [comment]
@Insire could you check if https://www.myget.org/feed/cake/package/nuget/Cake.Bakery/0.1.2-beta0001 works for you?

**Comment by Insire** [comment]
@mholo65 works flawlessly 

![image](https://user-images.githubusercontent.com/11455827/32735701-bdc8e5a6-c895-11e7-95d3-68603da39ea1.png)

**Comment by mholo65** [comment]
@Insire thanks! Will try pushing 0.1.2 out later tonight then!

**Comment by mholo65** [comment]
Fixed in #82

**Comment by Marusyk** [comment]
Doesn't work in 0.3.0

**Comment by mholo65** [comment]
@Marusyk, could you please open a new issue containing minimal steps to reproduce and verbose logs from VS Code / OmniSharp? You can set log level by specifying `”omnisharp.loglevel” : ”trace”` in your VS Code workspace settings. Thanks!
