### ISSUE TITLE
Errors from #loaded scripts erroneously shown in the current script

### ISSUE THREAD

**Issue by jnm2** [cake-build/bakery#90]
My build.cake has three `#load` directives. The first one happens to be loading a script ("lib.cake") which OmniSharp is reporting errors for. (It shouldn't be giving errors for that file, but I think it's another case of https://github.com/cake-build/bakery/issues/86. It's failing to find any of the types I'm using under `System.Net.Http`.)

In any case, red squiggles are showing up in build.cake which do not line up with actual code and which have the error messages from `lib.cake`. When I actually open `lib.cake`, I see the squiggles in the exact same positions on the screen but now as you'd expect they line up with code and the error messages make sense now that they are in context.

After opening `lib.cake`, the squiggles have disappeared from `build.cake`.

**Comment by mholo65** [comment]
Fixed in OmniSharp
